### ISSUE TITLE
Reloaded v2.00: Reverse mode not working (encfs crashes)

### ISSUE THREAD

**Issue by ThelloD** [kriswebdev/encfs4win-reloaded#2]
The command *encfs.exe --reverse [folder] [directory/Drive letter]* is not working with encfs4win-reloaded v2.00.

When I try to access the (live) encrypted folder, a Windows message pops up saying "encfs is not responding".
However it's working fine with v1.00.

I'm using Windows 10 Threshold 2 and Dokany V0.7.4.

Just FYI: 
Using the latest Dokany V0.8RC3 doesn't work at all and results in an OS crash (one screen turns black, the other one freezes). Don't know whether this is an encfs4win-reloaded related bug or an Dokany related bug.

**Comment by kriswebdev** [comment]
Hi @ThelloD

I confirm this issue.
Reloaded v2 is based on @jetwhiz fork so I guess he has the same issue.

I can't do tests right now, but we will need advanced debugging (that will involve more system crash... so a virtual machine is recommended) to go further.

The development branch now offers debugging ouput for encfs and dokany, so w'll need the logs using this [v2 dev](https://github.com/kriswebdev/encfs4win-reloaded/blob/dev/bin/encfs4win.zip]) using `encfs -f -v -d` flags.

**Comment by kriswebdev** [comment]
Debug traces:

v2:
```
###Create 0005
   CreateDisposition 0x00000001
CreateFile : \
        AccessMode: FILE_READ_ATTRIBUTES
        ShareMode: FILE_SHARE_DELETE|FILE_SHARE_WRITE|FILE_SHARE_READ
        Disposition: OPEN_EXISTING (3)
        Flags: 0 (0x0)
21:39:49 (DirNode.cpp:668) created FileNode for c:\temp\vis/ -- ouput moved up for readability
21:39:49 (encfs.cpp:139) getattr c:\temp\vis/ -- ouput moved up for readability
21:39:49 (compatwin.cpp:478) NOTIFY -- unix::stat -- ouput moved up for readability
###Create 0006
   CreateDisposition 0x00000001
CreateFile : \desktop.ini
        AccessMode: FILE_GENERIC_READ
        ShareMode: FILE_SHARE_DELETE|FILE_SHARE_WRITE|FILE_SHARE_READ
        Disposition: OPEN_EXISTING (3)
        Flags: 0 (0x0)
21:39:49 (compatwin.cpp:601) NOTIFY -- utf8_to_wfn
21:39:49 (BlockNameIO.cpp:193) Rejecting filename 'desktop.ini'
CreateFile status = 0
###GetFileInfo 0005
GetFileInfo : \
(Program crashes)
```

v1:
```
###Create 0005
   CreateDisposition 0x00000001
CreateFile : \
        AccessMode: FILE_READ_ATTRIBUTES
        ShareMode: FILE_SHARE_DELETE|FILE_SHARE_WRITE|FILE_SHARE_READ
        Disposition: OPEN_EXISTING (3)
        Flags: 0 (0x0)
20:55:19 (..\encfs\DirNode.cpp:780) created FileNode for c:\temp\vis/
20:55:19 (..\encfs\encfs.cpp:134) getattr c:\temp\vis/
CreateFile status = 0
###Create 0006
   CreateDisposition 0x00000001
CreateFile : \desktop.ini
        AccessMode: FILE_GENERIC_READ
        ShareMode: FILE_SHARE_DELETE|FILE_SHARE_WRITE|FILE_SHARE_READ
        Disposition: OPEN_EXISTING (3)
        Flags: 0 (0x0)
20:55:19 (..\encfs\encfs.cpp:141) error caught in getattr
CreateFile status = -2
###GetFileInfo 0005
GetFileInfo : \
20:55:19 (..\encfs\DirNode.cpp:780) created FileNode for c:\temp\vis/
20:55:19 (..\encfs\encfs.cpp:134) getattr c:\temp\vis/
###Create 0007
   CreateDisposition 0x00000001
CreateFile : \
        AccessMode: SYNCHRONIZE|FILE_READ_ATTRIBUTES|FILE_READ_DATA
        ShareMode: FILE_SHARE_DELETE|FILE_SHARE_WRITE|FILE_SHARE_READ
        Disposition: OPEN_EXISTING (3)
        Flags: 0 (0x0)
20:55:19 (..\encfs\DirNode.cpp:780) created FileNode for c:\temp\vis/
20:55:19 (..\encfs\encfs.cpp:134) getattr c:\temp\vis/
CreateFile status = 0
###Cleanup 0005
Cleanup: \

###GetFileInfo 0007
GetFileInfo : \
20:55:19 (..\encfs\DirNode.cpp:780) created FileNode for c:\temp\vis/
20:55:19 (..\encfs\encfs.cpp:134) getattr c:\temp\vis/
  unknown type:55
###Close 0005
Close: \

###Create 0008
   CreateDisposition 0x00000001
CreateFile : \
        AccessMode: FILE_READ_ATTRIBUTES
        ShareMode: FILE_SHARE_DELETE|FILE_SHARE_WRITE|FILE_SHARE_READ
        Disposition: OPEN_EXISTING (3)
        Flags: 0 (0x0)
20:55:19 (..\encfs\DirNode.cpp:780) created FileNode for c:\temp\vis/
20:55:19 (..\encfs\encfs.cpp:134) getattr c:\temp\vis/
CreateFile status = 0
###FindFiles 0007
FindFiles :\
20:55:19 (..\encfs\DirNode.cpp:780) created FileNode for c:\temp\vis/
20:55:19 (..\encfs\encfs.cpp:134) getattr c:\temp\vis/
20:55:19 (..\encfs\encfs.cpp:215) getdir on c:\temp\vis/
20:55:19 (..\encfs\DirNode.cpp:780) created FileNode for c:\temp\vis/.encfs6.xml
20:55:19 (..\encfs\encfs.cpp:134) getattr c:\temp\vis/.encfs6.xml
etc...
```
Two things to investigate:
- CreateFile : \desktop.ini (###Create 0006)
    - In v2, CreateFile desktop.ini on the crypted drive succeeds with status 0 while BlockNameIO rejects the file, possibly leading or the crash (or not!).
    - In v1, CreateFile desktop.ini on the crypted drive fails with status = -2.
- GetFileInfo : \ (###GetFileInfo 0005)
    - In v2, crash happens after Dokany "GetFileInfo : \" and before encfs confirms FileNode creation.
    - In v1, GetFileInfo : \" succeeds with encfs confirmation "(..\encfs\DirNode.cpp:780) created FileNode for <plain_dir>"

**Comment by kriswebdev** [comment]
This is now fixed in v2.01 release. It was due to bad rLog re-implementation causing crashes while throwing ERROR()'s. jetwhiz upstream repository is clean.

You can now use reverse mode with latest encfs 1.9.0 on Windows!

**Comment by janmattfeld** [comment]
Hi,

the reverse mode still does not work for me with the current release [v2.01](https://github.com/kriswebdev/encfs4win-reloaded/releases/tag/v2.01): The encrypted files are listed but cannot be accessed - File not found error. 

I am using Windows 10 x64 and installed the dependencies as listed in the release notes.

Debug Log:

> ###Create 0069
   CreateDisposition 0x00000001
CreateFile : \1E8MW6SFGK1BXRSHKMFPALYN
        AccessMode: SYNCHRONIZE|FILE_READ_ATTRIBUTES|FILE_EXECUTE|FILE_READ_EA|0x200
        ShareMode: FILE_SHARE_DELETE|FILE_SHARE_WRITE|FILE_SHARE_READ
        Disposition: OPEN_EXISTING (3)
        Flags: 0 (0x0)
17:49:49 (BlockNameIO.cpp:224) padding, _bx, finalSize = 121, 16, -105
17:49:49 (encfs.cpp:152) withFileNode: error caught in getattr: invalid padding size
CreateFile status = -2
###Create 0070
   CreateDisposition 0x00000001
CreateFile : \
        AccessMode: SYNCHRONIZE|FILE_READ_ATTRIBUTES
        ShareMode: FILE_SHARE_WRITE|FILE_SHARE_READ
        Disposition: OPEN_EXISTING (3)
        Flags: 0 (0x0)
17:49:49 (DirNode.cpp:668) created FileNode for D:\tmp\test/
17:49:49 (encfs.cpp:139) getattr D:\tmp\test/
17:49:49 (compatwin.cpp:478) NOTIFY -- unix::stat
17:49:49 (compatwin.cpp:601) NOTIFY -- utf8_to_wfn
CreateFile status = 0
###Cleanup 0070
[...]

_ (encfs.cpp:152) withFileNode: error caught in getattr: invalid padding size_ raises my attention.

**Comment by kriswebdev** [comment]
Hi janmattfeld.

Sorry, no time to investigate right now.
Are you using a full path for the plain dir folder and a driver letter for the encrypted (reverse) view?

Also, you should try jetwhiz release, maybe it's not affected.
https://github.com/jetwhiz/encfs4win/releases

**Comment by jetwhiz** [comment]
I can confirm that this behavior exists on encfs4win as well.  The issue appears to come from upstream, from the original encfs project.  I have created an issue in encfs4win based on this one to investigate the best course of action: https://github.com/jetwhiz/encfs4win/issues/8
 
I believe that this bug is fixed on encfs4win now, but I want to coordinate with upstream to ensure that my fix of their codebase is done appropriately.

**Comment by jetwhiz** [comment]
@janmattfeld -- did you choose "Block" or "Block32" for the filename encoding when you set up your partition?

**Comment by janmattfeld** [comment]
Hi jetwhiz,

thanks for your reply. I used the default setting. Manually choosing _Block32_ or _Null_ resolves the issue. 

However, I also had to make sure to disable _per-file initialization vectors_. They lead to the folowing error:

> ###QueryVolumeInfo 0157
GetVolumeInformation
###Read 0157
ReadFile : \K5JWAQA7FSYU4IT4CKRTHORUFNLIJ from 0 len 26
09:21:57 (encfs.cpp:139) read D:\tmp\test/test.txt
09:21:57 (CipherFileIO.cpp:470) handling reverse unique IV read: offset=0, dataLen=26
09:21:58 (compatwin.cpp:478) NOTIFY -- unix::stat
09:21:58 (compatwin.cpp:601) NOTIFY -- utf8_to_wfn
09:21:58 (CipherFileIO.cpp:283) Assert failed: ino != 0
09:21:58 (encfs.cpp:152) withFileNode: error caught in read: ino != 0

**Comment by jetwhiz** [comment]
The Block32 issue for Windows and Mac should be fixed in the next version of encfs (we're still working on adding the changes upstream).  After the next version, the default settings should automatically choose Block32 for Win/Mac.  Note that you'll have to re-encrypt your old installations manually to choose Block32, however. 

The remaining issue you describe relates to Dokany's readonly support.  I have written a patch to fix this (https://github.com/jetwhiz/encfs4win/commit/ff99b4934e5a98e934f0601fec47ad1a89c1cb5b), but am waiting for the Block/Block32 issues to be fixed upstream before pushing them to encfs4win.

**Comment by jetwhiz** [comment]
@janmattfeld - can you verify that this issue is fixed with the latest version of encfs4win? 

https://github.com/jetwhiz/encfs4win/releases

**Comment by janmattfeld** [comment]
Yes, v1.9.0-RC2 fixes the issue. Thanks!

**Comment by kriswebdev** [comment]
Thanks @jetwhiz 

Since your release now provides almost everything including rLog, dokany 1-based release, and bug corrections, I see no point of maintaining encfs4win-reloaded anymore except for the build system. Moreover, rLog has been de-implemeted and re-implemented in your project in a different way than original project, making any upstream merge a painful loss of time.

So I've made redirects to your project in README and Releases pages.

Two things in my mind:
- Building system need to be simple for the project and its dependencies, like 1-step build or scripted build. If I have time, I'd like to provide a build script based on upstream repos.
- Whenever you'll implement boost 1.60, keep in mind that binaries needs to be built from source, unlike 1.59. That increases build efforts.

 Thanks for your efforts in encfs4win development and keep up the good work.

**Comment by jetwhiz** [comment]
Hey @kriswebdev 

I've been trying to pull together a build system that will handle all of the prerequisites, but as soon as encfs switches to libgcrypt it will become a bit of a nightmare to build.  

I've released a rough draft of the build system that I've been working on, which you can see here: https://github.com/jetwhiz/encfs4win/commit/a26d62ee4e1772879aeed449bc27fe40289db00b.  It still needs a bit of work and needs to be made more user-friendly, though.  Maybe you can take a look and give me some feedback when you have time? 

I decided not to include the prerequisites as submodules in the encfs4win project, since the boost library is very large (around 1.5 GB) and it became a nightmare every time I switched branches (since my git environment auto-syncs all of the submodules).  The build tool will instead just clone the repositories it needs and puts them in the deps\ folder.
